[package]
name = "string-alloc"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
pprof = { version = "=0.13.0", features = ["criterion", "flamegraph", "prost", "protobuf", "protobuf-codec"] }
